spring.application.name=Desafio2
server.port=8081

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:micro2
spring.datasource.username=grupo4
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/micro2-console

springdoc.swagger-ui.path=/docs-micro2.html
springdoc.api-docs.path=/docs-micro2
springdoc.packagesToScan=org.compass.desafio2.controlador
